pyxword_contest/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def member():
    """List members."""
    return render_template(
        'users/member.html',
    )

pyxword_contest/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>Authorization required</h1>
        <p>
            Please <a href="{{ url_for('public.login', next=request.path) }}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

pyxword_contest/templates/footer.html
<footer>
    All rights reserved © 2017 <a href="https://stxnext.com/">STX Next</a>
</footer>

pyxword_contest/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    pyxword
  
    {% endblock %}
  </title>
  <link rel="shortcut icon" type="image/png" href="{{ asset_url_for('img/favicon128.png') }}"/>

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<section class="content">

  <div role="main" class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</section><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

pyxword_contest/templates/nav.html
<nav class="navbar" role="navigation">
  <div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div>
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}" class="btn-like">Welcome</a></li>
      {% if contest %}
        <li><a href="{{ url_for('contest.challenge', contest_slug=contest.slug) }}" class="btn-like">Challenge</a></li>
        {% if contest.rules %}
        <li><a href="{{ url_for('contest.rules', contest_slug=contest.slug) }}" class="btn-like">Rules</a></li>
        {% endif %}
        <li><a href="{{ url_for('contest.stats', contest_slug=contest.slug) }}" class="btn-like">Hall of Fame</a></li>
      {% endif %}
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text">
                <a href="{{ url_for('user.member') }}">Playing as <em>{{ current_user.display_name or current_user.email }}</em></a>
            </p>
        </li>
        <li>
            <p class="navbar-text">
                <a href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a>
            </p>
        </li>
    </ul>
    {% else %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.login') }}">Login</a></li>
      <li><a href="{{ url_for('public.register') }}">Register</a></li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>